# Generated by Django 4.1.2 on 2022-10-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activites',
            new_name='Activite',
        ),
    ]
